(WIP) Add feature for polarity using SentiWordnet
wiki-ai/draftquality pull request #3
Opened 2017-06-12 13:06 UTC by codez266

Adds a library sentiment_classifier that makes use of SentiWordnet and
WSD to detect the polarity of each word in a document and returns an
aggregate positive and negative score per document. Add these polarity
scores as features to enwiki.py

2017-06-12 14:50 UTC, halfak requested changes

2017-06-12 14:50 UTC, halfak commented on draftquality/feature_lists/enwiki.py
> +    return senti_classifier.polarity_scores(doc[:20])
Only the first 20 chars?

2017-06-12 14:55 UTC, codez266 commented on draftquality/feature_lists/enwiki.py
> +    return senti_classifier.polarity_scores(doc[:20])
First 20 sentences. The polarity_scores method by default takes a list of sentences as a document. Hence, I'm first splitting the text at '\n' and passing the first 20 sentences as input.
See - https://github.com/kevincobain2000/sentiment_classifier/#library-usage

2017-06-12 16:38 UTC, codez266 commented on draftquality/feature_lists/enwiki.py
> +    return senti_classifier.polarity_scores(doc[:20])
I'll see if I can make any quick performance improvements and ping again, before you test on a larger dataset.

2017-06-21 12:20 UTC, codez266 commented
Now taking only the most common word sense for polarity to improve computation. Ready for testing on a bigger dataset.

2017-06-29 01:21 UTC, adamwight commented
@codez266 fyi, I'm still struggling to learn the toolchain.  I've run small 10k samples through training and testing, but pretty sure I did something wrong or simply don't understand what's happening, because it claims an accuracy of 94%.  See https://phabricator.wikimedia.org/P5648

2017-06-30 00:42 UTC, adamwight reviewed
Looking really good!  I'm still running the model health check...

2017-06-30 00:42 UTC, adamwight commented on draftquality/feature_lists/enwiki.py
> +    pos, neg = 0, 0
I had to change these to 0.0 in order to get floats out.

2017-06-30 00:42 UTC, adamwight commented on draftquality/feature_lists/enwiki.py
>  draft_quality = (char_based + token_based + parse_based +
An extremely tiny thing I noticed for next time: It's helpful to leave the baseline feature list unchanged, and add a second feature list like "draft_quality_with_sentiment" for ease of building a side-by-side comparison.

2017-06-30 00:42 UTC, adamwight commented on draftquality/feature_lists/enwiki.py
> +from nltk.corpus import sentiwordnet as swn
Please add a note in the README, letting the user know to download the sentiwordnet nltk package...

2017-07-03 18:05 UTC, Pix1234 commented
author's request

2017-07-03 18:05 UTC, closed without merging